---
- name: Rolling update
  hosts: w
  become: true
  vars:
    ansible_become_pass: 
  tasks:
    - name: Latest package is installed
      ansible.builtin.apt:
        name: apache2
        state: latest
      notify: restart apache

  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
