---
- name: install docker
  hosts: w
  become: true
  vars:
    ansible_become_password: 
  tasks:
    - name: install apt-transport-https and other prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: add Docker's official GPG key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: add Docker repository to APT sources
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
        state: present
        filename: docker

    - name: install Docker packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true
