---
- name: hostnames demo
  hosts: w
  gather_facts: true
  tasks:
    - name: print_inventory_names
      ansible.builtin.debug:
        var: inventory_hostname
    - name: print ansible_hostname
      ansible.builtin.debug:
        var: ansible_hostname
    - name: print ansible_fqdn
      ansible.builtin.debug:
        var: ansible_fqdn