---
- name: unarchive file module
  hosts: w
  become: false
  vars: 
    myurl: "https://github.com/lucab85/ansible-pilot/archive/refs/heads/master.zip"
  tasks:
    - name: extractor presents
      ansible.builtin.apt:
        name:
          - unzip
          - tar
        state: present
      become: true
      vars:
        ansible_become_pass: 
    - name: extract archive
      ansible.builtin.unarchive:
        src: "{{myurl}}"
        dest: './downloads/'
        remote_src: true
        validate_certs: true