---
- name: Install and configure Apache
  hosts: all
  become: true
  tasks:
    - name: Update the apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache and development tools
      ansible.builtin.apt:
        name:
          - apache2
          - apache2-dev
        state: present

    - name: Copy apache2.conf
      ansible.builtin.copy:
        src: /path/to/your/local/httpd.conf
        dest: /etc/apache2/apache2.conf
        backup: yes

    - name: Copy 000-default.conf
      ansible.builtin.copy:
        src: /path/to/your/local/httpd-vhosts.conf
        dest: /etc/apache2/sites-available/000-default.conf
        backup: yes

    - name: Ensure Apache is started and enabled at boot
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes
